spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: mysql
    password: mysql
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
  pid:
    file: /usr/projects/im/app.pid
logging:
  level:
    root: info
file-backup-path: /usr/projects/im/files/
server:
  port: 80