spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: password
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
  pid:
    file: D:/springboot/app.pid
logging:
  level:
    root: info
file-backup-path: D:/im-files/